// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import { defineConfig, env } from 'prisma/config'

// Load the single repo-root .env (see PROJECT_PLAN.md §13). Prisma runs this config
// with cwd at apps/api, so resolve the root .env relative to this file.
const here = dirname(fileURLToPath(import.meta.url))
config({ path: resolve(here, '../../.env') })

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
})
